/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc_mhs_service_GUI.program;

import jdbc_mhs_service_GUI.model.Mahasiswa;
import jdbc_mhs_service_GUI.service.MysqlMahasiswaService;

/**
 *
 * @author ASUS
 */

import javax.swing.*;
import java.util.*;
public class JFrameUtama extends javax.swing.JFrame {
    DefaultListModel<String> dlmNama; 
    DefaultListModel<String> dlmId; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
         this.dlmNama = new DefaultListModel<>();
         this.dlmId = new DefaultListModel<>();
         this.jListNama.setModel(dlmNama);
         this.jListId.setModel(dlmId);
          jListId.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int index = jListId.getSelectedIndex();
            if (index >= 0) {
                // Isi textfield ID dan Nama di bagian Edit
                jTextFieldIdEdit.setText(dlmId.getElementAt(index));
                jTextFieldNamaEdit.setText(dlmNama.getElementAt(index));
                
                // Isi textfield ID dan Nama di bagian Hapus
                jTextFieldIdHapus.setText(dlmId.getElementAt(index));
                jTextFieldNamaHapus.setText(dlmNama.getElementAt(index));
            }
        }
    });
    }

     private void addItem(int id, String namaItem){
        dlmNama.addElement(namaItem);
        dlmId.addElement(String.valueOf(id));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAmbilSemuaData = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTambahkan = new javax.swing.JButton();
        jTextFieldIdEdit = new javax.swing.JTextField();
        jTextFieldIdHapus = new javax.swing.JTextField();
        jTextFieldNamaHapus = new javax.swing.JTextField();
        jTextFieldNamaEdit = new javax.swing.JTextField();
        jHapus = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jResetIndex = new javax.swing.JButton();
        jLabelReset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListId);

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA");

        jLabel3.setText("KELOLA DATA MAHASISWA");

        jAmbilSemuaData.setText("Ambil Semua Data");
        jAmbilSemuaData.addActionListener(this::jAmbilSemuaDataActionPerformed);

        jLabel4.setText("Nama : ");

        jTextFieldNama.addActionListener(this::jTextFieldNamaActionPerformed);

        jTambahkan.setText("Tambahkan");
        jTambahkan.addActionListener(this::jTambahkanActionPerformed);

        jHapus.setText("Hapus");
        jHapus.addActionListener(this::jHapusActionPerformed);

        jEdit.setText("Edit");
        jEdit.addActionListener(this::jEditActionPerformed);

        jResetIndex.setText("Reset Index");
        jResetIndex.addActionListener(this::jResetIndexActionPerformed);

        jLabelReset.setText("Index direset ke 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jAmbilSemuaData)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTambahkan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEdit)
                    .addComponent(jHapus))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jResetIndex)
                .addGap(18, 18, 18)
                .addComponent(jLabelReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jAmbilSemuaData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTambahkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEdit))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHapus))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResetIndex)
                    .addComponent(jLabelReset))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        dlmId.clear();
        dlmNama.clear();
      MysqlMahasiswaService service = new MysqlMahasiswaService();
      List<Mahasiswa> list = service.getAll();
       for (Mahasiswa m : list) {
        addItem(m.getId(), m.getNama());
    }

        
    }//GEN-LAST:event_jAmbilSemuaDataActionPerformed

    private void jTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahkanActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText().trim();
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setNama(nama);
        service.add(mhs);
        List<Mahasiswa> list = service.getAll();
        addItem(list.get(list.size()-1).getId(), nama);
   
    
        
        jTextFieldNama.setText("");

    }//GEN-LAST:event_jTambahkanActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
        int index = jListId.getSelectedIndex();
        String namaBaru = jTextFieldNamaEdit.getText().trim();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
        Mahasiswa mhs = service.makeMhsObject();
        mhs.setId(id);
        mhs.setNama(namaBaru);
        service.update(mhs);
        dlmNama.setElementAt(namaBaru, index);
          jTextFieldIdEdit.setText("");
            jTextFieldNamaEdit.setText("");
                
              
            jTextFieldIdHapus.setText("");
            jTextFieldNamaHapus.setText("");
        
        
    }//GEN-LAST:event_jEditActionPerformed

    private void jResetIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetIndexActionPerformed
        // TODO add your handling code here:
        MysqlMahasiswaService service = new MysqlMahasiswaService();
       
        if(service.isEmpty()) {
            service.indexReset();
            jLabelReset.setText("Index direset ke 1");
        }else {
            JOptionPane.showMessageDialog(this,
            "Tabel tidak kosong!\nHapus semua data dulu.",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
            
        }
           
    }//GEN-LAST:event_jResetIndexActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        int index = jListId.getSelectedIndex();
        int id = Integer.parseInt(dlmId.getElementAt(index));
        MysqlMahasiswaService service = new MysqlMahasiswaService();
         service.delete(id);
         dlmNama.removeElementAt(index);
         dlmId.removeElementAt(index);
         
                jTextFieldIdEdit.setText("");
                jTextFieldNamaEdit.setText("");
                
                
                jTextFieldIdHapus.setText("");
                jTextFieldNamaHapus.setText("");
        
    }//GEN-LAST:event_jHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAmbilSemuaData;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JButton jResetIndex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jTambahkan;
    private javax.swing.JTextField jTextFieldIdEdit;
    private javax.swing.JTextField jTextFieldIdHapus;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNamaEdit;
    private javax.swing.JTextField jTextFieldNamaHapus;
    // End of variables declaration//GEN-END:variables
}
