/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Latihan_JFrame;

/**
 *
 * @author ASUS
 */

import javax.swing.*;
import java.util.*;
public class Proyek3 extends javax.swing.JFrame {
    
    List<String> dataList = new ArrayList<>();
    Set<String> dataSet = new HashSet<>();
    Map<Integer,String> dataMap = new HashMap<>();
    DefaultListModel<String> dlm; 
    int key = 1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proyek3.class.getName());

    /**
     * Creates new form Proyek3
     */
    public Proyek3() {
        initComponents();
         this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
    }
    
    
     private void addItem(String namaItem){
        dlm.addElement(namaItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jSaveList = new javax.swing.JButton();
        jInsertDataList = new javax.swing.JButton();
        jSaveSet = new javax.swing.JButton();
        jInsertDataSet = new javax.swing.JButton();
        jSaveMap = new javax.swing.JButton();
        jInsertDataMap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jClearAll = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jLabelList = new javax.swing.JLabel();
        jLabelSet = new javax.swing.JLabel();
        jLabelMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jSaveList.setText("Save to List ->");
        jSaveList.addActionListener(this::jSaveListActionPerformed);

        jInsertDataList.setText("<- Insert Data List");
        jInsertDataList.addActionListener(this::jInsertDataListActionPerformed);

        jSaveSet.setText("Save to Set ->");
        jSaveSet.addActionListener(this::jSaveSetActionPerformed);

        jInsertDataSet.setText("<- Insert Data Set");
        jInsertDataSet.addActionListener(this::jInsertDataSetActionPerformed);

        jSaveMap.setText("Save to Map ->");
        jSaveMap.addActionListener(this::jSaveMapActionPerformed);

        jInsertDataMap.setText("<- Insert Data Map");
        jInsertDataMap.addActionListener(this::jInsertDataMapActionPerformed);

        jLabel1.setText("Item Name : ");

        jTextField.addActionListener(this::jTextFieldActionPerformed);

        jClearAll.setText("Clear All");
        jClearAll.addActionListener(this::jClearAllActionPerformed);

        jAdd.setText("Add");
        jAdd.addActionListener(this::jAddActionPerformed);

        jUpdate.setText("Update");
        jUpdate.addActionListener(this::jUpdateActionPerformed);

        jDelete.setText("Delete");
        jDelete.addActionListener(this::jDeleteActionPerformed);

        jLabelList.setText("Data Tersimpan : 0");

        jLabelSet.setText("Data Tersimpan : 0");

        jLabelMap.setText("Data Tersimpan : 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSaveList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertDataList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSaveSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertDataSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSaveMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertDataMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelList)
                                    .addComponent(jLabelSet)
                                    .addComponent(jLabelMap)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDelete)))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveList)
                            .addComponent(jLabelList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveSet)
                            .addComponent(jLabelSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveMap)
                            .addComponent(jLabelMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataMap)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearAll)
                    .addComponent(jAdd)
                    .addComponent(jUpdate)
                    .addComponent(jDelete))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllActionPerformed
        // TODO add your handling code here:
          dlm.clear();
    }//GEN-LAST:event_jClearAllActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        addItem(jTextField.getText());
        jTextField.setText("");  
    }//GEN-LAST:event_jAddActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
         int index = jListItem.getSelectedIndex();
        String selected = jTextField.getText();
         dlm.setElementAt(selected, index);
        jTextField.setText("");
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        jTextField.setText("");
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveListActionPerformed
        // TODO add your handling code here:
        dataList.clear();
        for(int i = 0; i < dlm.getSize(); i++) {
            dataList.add(dlm.getElementAt(i));
        }
        jLabelList.setText("Data Tersimpan : " + dataList.size());
        
        
    }//GEN-LAST:event_jSaveListActionPerformed

    private void jInsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataListActionPerformed
        // TODO add your handling code here:
        
        for(String data : dataList) {
            dlm.addElement(data);
        }
        
    }//GEN-LAST:event_jInsertDataListActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jSaveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveSetActionPerformed
        // TODO add your handling code here:
        dataSet.clear();
        for(int i = 0; i < dlm.getSize(); i++) {
            dataSet.add(dlm.getElementAt(i));
        }
        jLabelSet.setText("Data Tersimpan : " + dataSet.size());
    }//GEN-LAST:event_jSaveSetActionPerformed

    private void jInsertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataSetActionPerformed
        // TODO add your handling code here:
          for(String data : dataSet) {
            dlm.addElement(data);
        }
        
    }//GEN-LAST:event_jInsertDataSetActionPerformed

    private void jSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveMapActionPerformed
        // TODO add your handling code here:
        dataMap.clear();
        key = 1; // reset key
        for (int i = 0; i < dlm.getSize(); i++) {
            dataMap.put(key++, dlm.getElementAt(i));
        }
        jLabelMap.setText("Data Tersimpan : " + dataMap.size());
        
    }//GEN-LAST:event_jSaveMapActionPerformed

    private void jInsertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataMapActionPerformed
        // TODO add your handling code here:
        for(int key : dataMap.keySet()) {
            dlm.addElement(dataMap.get(key));
        }
        
    }//GEN-LAST:event_jInsertDataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Proyek3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jClearAll;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jInsertDataList;
    private javax.swing.JButton jInsertDataMap;
    private javax.swing.JButton jInsertDataSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JLabel jLabelSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JButton jSaveList;
    private javax.swing.JButton jSaveMap;
    private javax.swing.JButton jSaveSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
